/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-UConn2402
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_UCONN2402_API_H
#define INCLUDED_UCONN2402_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_UConn2402_EXPORTS
#define UCONN2402_API __GR_ATTR_EXPORT
#else
#define UCONN2402_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_UCONN2402_API_H */
