/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ArbitrarySync2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c7f1b385f089a885c7c3b4166b1e1e3a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/UConn2402/ArbitrarySync2.h>
// pydoc.h is automatically generated in the build directory
#include <ArbitrarySync2_pydoc.h>

void bind_ArbitrarySync2(py::module& m)
{

    using ArbitrarySync2    = ::gr::UConn2402::ArbitrarySync2;


    py::class_<ArbitrarySync2, gr::block, gr::basic_block,
        std::shared_ptr<ArbitrarySync2>>(m, "ArbitrarySync2", D(ArbitrarySync2))

        .def(py::init(&ArbitrarySync2::make),
           py::arg("threshold"),
           py::arg("samples"),
           D(ArbitrarySync2,make)
        )
        



        ;




}








