/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(CrossCorrDown.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9109e67fc06c0d1289cf6662e6dc0c09)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/UConn2402/CrossCorrDown.h>
// pydoc.h is automatically generated in the build directory
#include <CrossCorrDown_pydoc.h>

void bind_CrossCorrDown(py::module& m)
{

    using CrossCorrDown    = gr::UConn2402::CrossCorrDown;


    py::class_<CrossCorrDown, gr::block, gr::basic_block,
        std::shared_ptr<CrossCorrDown>>(m, "CrossCorrDown", D(CrossCorrDown))

        .def(py::init(&CrossCorrDown::make),
           D(CrossCorrDown,make)
        )
        



        ;




}








