/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Preamble.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(61e9dcb15f8b68ab97ac004f30855f11)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/UConn2402/Preamble.h>
// pydoc.h is automatically generated in the build directory
#include <Preamble_pydoc.h>

void bind_Preamble(py::module& m)
{

    using Preamble    = ::gr::UConn2402::Preamble;


    py::class_<Preamble, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<Preamble>>(m, "Preamble", D(Preamble))

        .def(py::init(&Preamble::make),
           py::arg("filename"),
           py::arg("pcklen"),
           D(Preamble,make)
        )
        



        ;




}








